version: "3.9"
services:
  php:
    image: php:8.1-apache
    container_name: php_app
    volumes:
      - ./php:/var/www/html  # Montez votre code PHP dans le container
    ports:
      - "8080:80"
    depends_on:
      - python_api

  python_api:
    build: ./python_api
    container_name: python_api
    ports:
      - "8000:8000"
    environment:
      - CUDA_HOME=/usr/local/cuda
    runtime: nvidia
    # image: nvidia/cuda:11.6.1-cudnn8-runtime-ubuntu20.04
    volumes:
      - ./models:/root/.cache/huggingface

